device: 0

misc:
  seed: 0

experiment:
  # image
  input_resolution: [224, 224]
  simclr_mlp: [512, 128, 512]
  simclr_temperature: 0.1
  # text
  dropout: 0.05
  eda_alpha: 0.05
  back_trans: true
  backtrans_p: 0.1
  text_length: 77
  # mix
  mixgen: false
  mixgen_type: cat  # ori or cat
  mixgen_p: 0.1
  mixgen_ratio: 0.1

  # loss
  nitc_ratio: 1.0
  ####
  ritc: true
  ritc_eps: 1.0e-2
  ritc_ratio: 1.0
  ####
  citc: true
  citc_lambda1: 2000 
  citc_lambda2: 0.
  citc_ratio: 0.1
  ####
  bai: true
  bai_ratio: 0.03
  ###
  lamda: 0.20
  ###
  ent: true
  ent_ratio: 0.1

schedule:
  lr: 0.8e-4 
  epoch: 5
  epoch_warmup: 1
  lr_start: 1.0e-6
  lr_end: 5.0e-7
  weight_decay: 0.02
  betas: [0.9, 0.98]
  eps: 1.0e-8
  ratio_factor: 5.0

model:
  ckpt_type: original_clip  # original_clip / saved
  saved_path: 'ckpts/s.baseline_224_224/RSTPReid'
  checkpoint: '/data/qch/TBPS/ViT-B-16.pt'    # e.g., '../../data/CLIP/ViT-B-16.pt'
  use_gather: true
  softlabel_ratio: 0.4
  embed_dim: 512
  vocab_size: 49408

log:
  print_period: 50

data:
  batch_size: 80
  test_batch_size: 256
  num_workers: 8

distributed:
  backend: nccl
  url: 'env://'

anno_dir: '/data/qch/TBPS/annotation/RSTPReid'    # e.g., 'data/CUHK-PEDES'
image_dir: '/data/qch/dataset/RSTPReid/imgs'     # e.g., '../../datasets/cuhkpedes/imgs'